### ISSUE TITLE
CSS 实现时钟效果

### ISSUE THREAD

**Issue by zhangsanshi** [zhangsanshi/issue-blog#41]
[链接](https://zhangsanshi.github.io/demo/clock.html)
主要逻辑
```css
@keyframes clock {
        0 {
            transform: rotate(0deg) translateZ(0);
        }
        100% {
            transform: rotate(360deg) translateZ(0);
        }
}
.clock-s {
        /* steps 60 */
        animation: clock 60s steps(60, end) infinite;
}
```
